server:
  port: 8000
#  servlet:
#      context-path: /scaffold/api

spring:
  application:
    name: llk-scaffold
  profiles:
    active: dev
  aop:
    auto: true

mybatis:
  type-aliases-package: com.llk.scaffold.model.entity
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

log:
  path: /data/apps/log/scaffold