spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scaffold?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000

      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20

      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: llk
        # IP白名单
        allow: 127.0.0.1
        #IP黑名单（共同存在时，deny优先于allow）
        #deny: 192.168.1.218

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000